name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: rust-latest
    steps:
    - uses: actions/checkout@v3
    - name: clippy
      run: cargo clippy --verbose -- -Dwarnings
    - name: rustfmt
      run: cargo +nightly fmt --check
    - name: test
      run: cargo test --verbose
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2

